# Etapa de construcción
FROM node:16 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de package.json y package-lock.json
COPY package.json package-lock.json /app/

# Instala las dependencias de Node.js
RUN npm install

# Copia todo el código fuente del frontend
COPY . /app

# Ejecuta el build para crear los archivos estáticos para producción
RUN npm run build

# Etapa de servidor de producción
FROM node:16-slim

# Instala 'serve' globalmente para servir la aplicación construida
RUN npm install -g serve

# Establece el directorio de trabajo para la etapa final
WORKDIR /app

# Copia los archivos construidos de la etapa anterior
COPY --from=build /app/build /app

# Exponer el puerto 5000 para servir la aplicación
EXPOSE 3001

# Comando para servir la aplicación con 'serve' en producción
CMD ["serve", "-s", ".", "-l", "3001"]
