# Usa una imagen base de Python
FROM python:3.9-slim

# Actualiza e instala las dependencias necesarias del sistema
RUN apt-get update && apt-get install -y libpq-dev

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo requirements.txt al contenedor
COPY ./backend/requirements.txt /app/

# Instala las dependencias desde requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código del backend al contenedor
COPY ./backend /app/

# Exponer el puerto en el que corre la aplicación Flask
EXPOSE 5000

# Define el comando para ejecutar la aplicación
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
