"""cambios en BD

Revision ID: 253ec607209c
Revises: af89c68e5404
Create Date: 2025-02-22 08:45:10.305562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253ec607209c'
down_revision = 'af89c68e5404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado_contable',
    sa.Column('id_estado_contable', sa.Integer(), nullable=False),
    sa.Column('tipo_estado_contable', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_estado_contable')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=30),
               existing_nullable=True)

    with op.batch_alter_table('trabajos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entrego', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('deuda', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estado_contable', sa.Integer(), nullable=True))
        batch_op.drop_constraint('trabajos_estado_trabajo_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'estado', ['estado'], ['id_estado'])
        batch_op.create_foreign_key(None, 'estado_contable', ['estado_contable'], ['id_estado_contable'])
        batch_op.drop_column('estado_trabajo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_trabajo', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('trabajos_estado_trabajo_fkey', 'estado', ['estado_trabajo'], ['id_estado'])
        batch_op.drop_column('estado_contable')
        batch_op.drop_column('estado')
        batch_op.drop_column('deuda')
        batch_op.drop_column('entrego')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)

    op.drop_table('estado_contable')
    # ### end Alembic commands ###
