"""Cambio en Clientes

Revision ID: af89c68e5404
Revises: 7df812202212
Create Date: 2025-01-21 21:00:40.961896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af89c68e5404'
down_revision = '7df812202212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint('clientes_cedula_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_unique_constraint('clientes_cedula_key', ['cedula'])

    # ### end Alembic commands ###
